version: '3.8'

services:
  supercowsay:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: supercowsay
    volumes:
      - ../test_results:/supercowsay/test_results
    environment:
      - TERM=xterm-256color
    command: ["The quick brown fox jumps over the lazy dog"]

  benchmark:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: supercowsay-benchmark
    volumes:
      - ../test_results:/supercowsay/test_results
    entrypoint: ["./rigorous_benchmark.sh"]
    privileged: true  # Required for perf

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: supercowsay-test
    volumes:
      - ../test_results:/supercowsay/test_results
    entrypoint: ["./correctness_tests.sh"]